services:
  db:
    image: mysql:8.4.5-oraclelinux9
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=cursos
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
